from __future__ import annotations

import logging
import uuid

import httpx
from fastapi import FastAPI, Request, Response, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from .config import ApiConfig
from .orchestrator_client import OrchestratorClient
from ..core_models import ChatResponse, ChatRequest
from ..logging_config import setup_logging
setup_logging("api-gateway")
log = logging.getLogger("api_gateway.app")

cfg = ApiConfig()
app = FastAPI(title="MicroChat Medical – API Gateway", version="1.0.0")

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=[o.strip() for o in cfg.cors_origins.split(",")] if cfg.cors_origins else ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

orch = OrchestratorClient(cfg)

@app.get("/health")
async def health() -> dict:
    """
    Handles the health check endpoint for the application.

    This function provides a simple health status for the application, typically
    used to verify if the service is running and reachable. It returns a JSON response
    indicating the health status.

    :return: A dictionary containing the health status of the application
    :rtype: dict
    """
    return {"ok": True}

@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest, request: Request, response: Response) -> ChatResponse:
    """
    Handles the /chat endpoint, processing a chat request and generating a response.

    This function serves as an entry point for handling chat-related requests. It extracts a
    unique request identifier from the headers or generates one if unavailable, associates it
    with the current request, and logs the interaction for tracing/debugging purposes. The endpoint
    asynchronously interacts with an upstream orchestrator to generate the desired chat response.
    If errors occur during this interaction, appropriate HTTP exceptions are raised to inform
    the client of the nature of the failure.

    Parameters:
    req: ChatRequest
        The incoming chat request payload containing parameters for generating the chat response.
    request: Request
        The FastAPI request object providing details about the HTTP request.
    response: Response
        The FastAPI response object used to set necessary headers.

    Returns:
    ChatResponse
        The chat response generated by the orchestrator based on the incoming chat request.

    Raises:
    HTTPException
        - With status 504 if the orchestrator times out in responding to the request.
        - With status 502 if receiving an HTTP error response from the orchestrator.
        - With status 502 for unexpected errors during request processing.
    """
    request_id = request.headers.get("X-Request-ID", str(uuid.uuid4()))
    response.headers["X-Request-ID"] = request_id

    # Store request_id in the request state so the Filter can read it
    request.state.request_id = request_id

    log.info(f"Incoming /chat request {request_id}")

    try:
        resp = await orch.chat(req, request_id=request_id)
        log.info(f"Outgoing /chat response OK {request_id}")
        return resp

    except httpx.TimeoutException as e:
        log.warning(f"Upstream timeout {request_id}: {e}")
        raise HTTPException(status_code=504, detail="Upstream timeout")

    except httpx.HTTPStatusError as e:
        log.error(f"Upstream HTTP error {request_id}: {e}")
        raise HTTPException(status_code=502, detail=f"Upstream error: {e.response.status_code}")

    except Exception as e:
        log.exception(f"Unexpected error in gateway {request_id}")
        raise HTTPException(status_code=502, detail="Upstream error")
